spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account-service
  security:
    user:
      name: user
      password: pass
#security:
#  basic:
#    enabled: false
#management:
#  security:
#    enabled: false

