spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account-service
  security:
    user:
      name: user
      password: pass
rates:
  url: http://data.fixer.io/api/latest
  access_key: 73c249c05d3e82587f244ac32c9b962a

server:
  port: 8081
